// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5HJw-A8GKz91Yx5brc26pxqrPJ9j7LT0',
    appId: '1:531705019045:web:e1b7784b1134e29316ab4c',
    messagingSenderId: '531705019045',
    projectId: 'plant-watering-reminder-1f917',
    authDomain: 'plant-watering-reminder-1f917.firebaseapp.com',
    storageBucket: 'plant-watering-reminder-1f917.firebasestorage.app',
    measurementId: 'G-YWZTPTF89B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2aR0yqEPoVGsSprIu8DYFddrDUW89XtQ',
    appId: '1:531705019045:android:ea40d21b1aa7307216ab4c',
    messagingSenderId: '531705019045',
    projectId: 'plant-watering-reminder-1f917',
    storageBucket: 'plant-watering-reminder-1f917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDThlNzh6Dc54nCPwIZ1yZ8r28GZbhZZl8',
    appId: '1:531705019045:ios:08ff01e45905a94b16ab4c',
    messagingSenderId: '531705019045',
    projectId: 'plant-watering-reminder-1f917',
    storageBucket: 'plant-watering-reminder-1f917.firebasestorage.app',
    iosBundleId: 'com.plantapp.plantWateringReminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5HJw-A8GKz91Yx5brc26pxqrPJ9j7LT0',
    appId: '1:531705019045:web:8ee772bd56870bfc16ab4c',
    messagingSenderId: '531705019045',
    projectId: 'plant-watering-reminder-1f917',
    authDomain: 'plant-watering-reminder-1f917.firebaseapp.com',
    storageBucket: 'plant-watering-reminder-1f917.firebasestorage.app',
    measurementId: 'G-Q2Q0KBTQJR',
  );
}
